-- Table: public.config

-- DROP TABLE public.config;

CREATE TABLE public.config
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Key" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Value" character varying(250) COLLATE pg_catalog."default",
    "Note" character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT config_pk PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.config
    OWNER to postgres;
