-- Table: public.goodsattr

-- DROP TABLE public.goodsattr;

CREATE TABLE public.goodsattr
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GoodsId" integer NOT NULL,
    "Name" character varying(250) COLLATE pg_catalog."default",
    "Value" character varying(500) COLLATE pg_catalog."default",
    "DisplayOrder" integer DEFAULT 0,
    CONSTRAINT goodsattr_pk PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.goodsattr
    OWNER to postgres;