-- Table: public.goodsattach

-- DROP TABLE public.goodsattach;

CREATE TABLE public.goodsattach
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GoodsId" integer NOT NULL,
    "Name" character varying(250) COLLATE pg_catalog."default",
    "Ext" character varying(50) COLLATE pg_catalog."default",
    "Size" integer DEFAULT 0,
    "Path" character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT goodsattach_pk PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.goodsattach
    OWNER to postgres;
