-- Table: public.goods

-- DROP TABLE public.goods;

CREATE TABLE public.goods
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(255) COLLATE pg_catalog."default",
    "Picture" character varying(255) COLLATE pg_catalog."default",
    "Info" character varying(500) COLLATE pg_catalog."default",
    "Description" text COLLATE pg_catalog."default",
    "DisplayOrder" integer DEFAULT 0,
    "Status" smallint DEFAULT 0,
    CONSTRAINT goods_pk PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.goods
    OWNER to postgres;